curl -H "Content-Type: application/json" -X POST -d '{"firstName":"John","lastName":"Smith", "email": "johnsmith@aol.com"}' http://localhost:3000/api/users

curl -H "Content-Type: application/json" -X POST -d '{"firstName":"Jane","lastName":"Doe", "email": "janedoe@aol.com"}' http://localhost:3000/api/users

curl -H "Content-Type: application/json" -X POST -d '{"firstName":"Jonathan","lastName":"Brown", "email": "jbrown@yahoo.com"}' http://localhost:3000/api/users

curl -H "Content-Type: application/json" -X POST -d '{"firstName":"Emily","lastName":"Johnson", "email": "ejohnson@unicorn.com"}' http://localhost:3000/api/users

curl -H "Content-Type: application/json" -X POST -d '{"firstName":"Samantha","lastName":"Jackson", "email": "sjackson@unicorn.com"}' http://localhost:3000/api/users

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"New Orleans LaserTag Party", "totalPeople": "30", "pricePerPerson":"35", "image_url": "https://s3-us-west-1.amazonaws.com/eventify-photos/laser-tag-square-500.jpg", "description":"An amazing night of lasertag that will include fun and drinks", "date": "2016-02-21 00:00:00", "addressLabel": "Laser Tag of Metairie, Veterans Memorial Boulevard, Metairie, LA, United States", "lat": "30.00500488281250", "long": "-90.18650054931640",  "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"New Orleans Amazing Race", "totalPeople": "200", "pricePerPerson":"20", "image_url": "https://s3-us-west-1.amazonaws.com/eventify-photos/scavenger-hunt-square-500.jpg", "description":"Come join our once-in-a-lifetime scavenger hunt where you can run around and be silly with a group of strangers and friends", "date": "2016-03-11 14:30:00", "addressLabel": "City Park, New Orleans, LA, United States", "lat": "30.00003242492676", "long": "-90.09570312500", "userId": "2"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"SanFran Sunset Charter Sail", "totalPeople": "30", "pricePerPerson":"40", "image_url": "https://eventify-photos.s3.amazonaws.com/SunsetSail.jpg", "description":"We are planning on renting a charter for a sunset sail on the pier. Come and join us to enjoy the beautiful San Francisco skyline", "date": "2016-06-26 17:00:00", "addressLabel": "Adventure Cat Sailing Charters, Pier 39 Concourse, San Francisco, CA, United States", "lat": "37.81087875366211", "long": "-122.41080474853516", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Space Needle Gala", "totalPeople": "100", "pricePerPerson":"100", "image_url": "https://eventify-photos.s3.amazonaws.com/SeattleSpaceNeedle.jpg", "description":"We are renting out the Space Needle for an elegant night involving an auction, a delicious dinner, and amazing cocktails", "date": "2016-04-08 20:00:00", "addressLabel": "Space Needle, Seattle, WA, United States", "lat": "47.62042236328125", "long": "-122.34935760498047", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Seattle Texas Holdem Tournament", "totalPeople": "100", "pricePerPerson":"75", "image_url": "https://eventify-photos.s3.amazonaws.com/PokerTourny.jpg", "description":"This is a Texas Holdem Tournament, winner takes all. Bring your best poker face.", "date": "2016-11-19 18:30:00", "addressLabel": "Tims Tavern on 105th, North 105th Street, Seattle, WA, United States", "lat": "47.70501708984375", "long": "-122.34516906738281", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Tailgating for Rodeo", "totalPeople": "100", "pricePerPerson":"20", "image_url": "https://eventify-photos.s3.amazonaws.com/SanRodeo.jpg", "description":"Come tailgate before the rodeo for some great Texas BBQ and beer, of course", "date": "2016-05-29 12:30:00", "addressLabel": "San Antonio Stock Show & Rodeo, AT&T Center Parkway, San Antonio, TX, United States", "lat": "29.43303871154785", "long": "-98.43379974365234", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"VIP Box at Cowboys Game", "totalPeople": "50", "pricePerPerson":"250", "image_url": "https://eventify-photos.s3.amazonaws.com/CowboyStadium.jpg", "description":"We are renting a private box at the cowboy playoff game. The event will have catered food and amazing seats to watch the game", "date": "2016-10-23 19:00:00", "addressLabel": "AT&T Stadium, AT&T Way, Arlington, TX, United States", "lat": "32.75366973876953", "long": "-97.08629608154297", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Dinner for a Cause", "totalPeople": "100", "pricePerPerson":"50", "image_url": "https://s3-us-west-1.amazonaws.com/eventify-photos/dinner-party-square-500.jpg", "description":"Come join a good cause and have some great food. The money will go to supporting the local community", "date": "2016-06-03 19:30:00", "addressLabel": "Kitchen 713, Canal Street, Houston, TX, United States", "lat": "29.82706832886", "long": "-95.04832458496", "userId": "3"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Houston Room Escape", "totalPeople": "10", "pricePerPerson":"25", "image_url": "https://s3-us-west-1.amazonaws.com/eventify-photos/escape-room-square-500.jpg", "description":"My girlfriend and I are interesting in doing this escape the room type game, and we need you to join to make the minimum person requirements!", "date": "2016-08-27 20:00:00", "addressLabel": "Houston Escape Room, Jackson Street, Houston, TX, United States", "lat": "29.74735641479", "long": "-95.36364746094", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Johns House Party", "totalPeople": "40", "pricePerPerson":"10", "image_url": "https://s3-us-west-1.amazonaws.com/eventify-photos/house-party-square-500.jpg", "description":"Hey guys, I plan on having a party at my house, but need help with the cost. The $10 will include finger food and a keg", "date": "2016-05-27 17:30:00", "addressLabel": "2527 Main Street, Houston, TX, United States", "lat": "29.74551582336", "long": "-95.37387847900", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Growing Your Own Vegetables Class", "totalPeople": "40", "pricePerPerson":"10", "image_url": "https://eventify-photos.s3.amazonaws.com/VegetableGarden.jpg", "description":"Join our class where a horticulture expert will teach you how to grow your own vegetable garden in the bay area!", "date": "2016-08-21 13:00:00", "addressLabel": "Sloat Garden Center, Sloat Boulevard, San Francisco, CA, United States", "lat": "37.73404312133789", "long": "-122.48902130126953", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Santa Cruz Surf Lessons", "totalPeople": "10", "pricePerPerson":"25", "image_url": "https://eventify-photos.s3.amazonaws.com/surfing.jpg", "description":"I am trying to get a small class together for surf lessons in Santa Cruz. Join if you are interested in learning how to surf!!", "date": "2016-09-11 14:30:00", "addressLabel": "Santa Cruz Surf School, Center Street, Santa Cruz, CA, United States", "lat": "36.97029876708984", "long": "-122.02760314941406", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Join a Mardi Gras Krewe", "totalPeople": "250", "pricePerPerson":"100", "image_url": "https://eventify-photos.s3.amazonaws.com/MardiGras.jpg", "description":"Here is your chance to join a Mardi Gras Krewe. We are starting a krewe, which will roll uptown on the Monday before Mardi Gras day. Come before spots run out! The krewe will be Disney themed", "date": "2016-03-05 15:00:00", "addressLabel": "Mardi Gras World, Port of New Orleans Place, New Orleans, LA, United States", "lat": "29.93493270874023", "long": "-90.06150054931640", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Area 21 Overnight LaserTag", "totalPeople": "30", "pricePerPerson":"30", "image_url": "https://eventify-photos.s3.amazonaws.com/LaserTag.jpg", "description":"Come join our overnight lasertag game! It will involve pizza and drinks, and all-night lasertag until you are all lasered out!!!", "date": "2016-03-19 23:00:00", "addressLabel": "Area 21 Laser Tag Arena, Texas 6, Houston, TX, United States", "lat": "29.79203414916992", "long": "-95.64479064941406", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Private Box for Houston Texans", "totalPeople": "50", "pricePerPerson":"250", "image_url": "https://eventify-photos.s3.amazonaws.com/houston-football.jpeg", "description":"We are renting out a private box for the Houston Texans game. Come join us for great seats, food, and drinks.", "date": "2016-010-27 16:00:00", "addressLabel": "NRG Stadium, Reliant Parkway, Houston, TX, United States", "lat": "29.68642616272", "long": "-95.40682983398", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Kids Ultimate Fitness Challenge!", "totalPeople": "100", "pricePerPerson":"20", "image_url": "https://eventify-photos.s3.amazonaws.com/kidsChallenge.jpeg", "description":"The Kids Ultimate Fitness Challenge is the nations largest mobile fitness event traveling from coast-to-coast dedicated to helping keep kids healthy and active.", "date": "2016-02-26 18:30:00", "addressLabel": "Mason Park, Houston, TX, United States", "lat": "29.77629089355469", "long": "-95.75038909912110", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Painless Paintball", "totalPeople": "25", "pricePerPerson":"45", "image_url": "https://eventify-photos.s3.amazonaws.com/CEP-17478.jpg", "description":"Lots of open space to run and play.  Covered staging/picnic areas.  Convenient air filling stations throughout the park.  A sky loft for parents to sit and watch their kids play on our two artificial turf airball fields.", "date": "2016-02-26 13:00:00", "addressLabel": "Urban War Zone Paintball, Telephone Road, Houston, TX, United States", "lat": "29.66961669921875", "long": "-95.28922271728516", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Growing Your Own Vegetables Class", "totalPeople": "40", "pricePerPerson":"10", "image_url": "https://eventify-photos.s3.amazonaws.com/VegetableGarden.jpg", "description":"Join our class where a horticulture expert will teach you how to grow your own vegetable garden in the bay area!", "date": "2016-08-21 13:00:00", "addressLabel": "River Oaks Plant House, Westheimer Road, Houston, TX, United States", "lat": "29.73704719543", "long": "-95.54299926758", "userId": "1"}' http://localhost:3000/api/events

curl -H "Content-Type: application/json" -X POST -d '{"eventName":"Texas Holdem Tournament", "totalPeople": "100", "pricePerPerson":"75", "image_url": "https://eventify-photos.s3.amazonaws.com/PokerTourny.jpg", "description":"This is a Texas Holdem Tournament, winner takes all. Bring your best poker face.", "date": "2016-11-19 18:30:00", "addressLabel": "Tejas Grill & Sports Bar, Lamar Street, Houston, TX, United States", "lat": "29.75675010681", "long": "-95.36640930176", "userId": "3"}' http://localhost:3000/api/events



